# Generated by Django 2.1.7 on 2019-02-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pokemon', '0001_initial'), ('pokemon', '0002_auto_20190223_2150'), ('pokemon', '0003_auto_20190223_2338'), ('pokemon', '0004_auto_20190223_2340'), ('pokemon', '0005_auto_20190224_0126'), ('pokemon', '0006_auto_20190224_0131'), ('pokemon', '0007_move_effect_percent_chance'), ('pokemon', '0008_auto_20190224_0342'), ('pokemon', '0009_auto_20190224_0352'), ('pokemon', '0010_auto_20190224_1642'), ('pokemon', '0011_auto_20190224_1840')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('BATTLE ITEMS', 'Battle Items'), ('BERRIES', 'Berries'), ('GENERAL ITEMS', 'General Items'), ('HOLD ITEMS', 'Hold Items'), ('MACHINES', 'Machines'), ('MEDICINE', 'Medicine'), ('POKEBALLS', 'Pokeballs'), ('UNKOWN', 'Uknown')], max_length=16, null=True)),
                ('effect', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Physical'), ('SPECIAL', 'Special'), ('STATUS', 'Status')], max_length=16, null=True)),
                ('power', models.IntegerField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('power_points', models.IntegerField()),
                ('tm', models.CharField(max_length=8, null=True)),
                ('effect', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('form', models.CharField(max_length=32, null=True)),
                ('hit_points', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('abilities', models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Ability')),
                ('moves', models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Move')),
                ('types', models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Type')),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemon',
                'ordering': ['pokedex', 'form'],
            },
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.Type'),
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name': 'ability', 'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'verbose_name': 'move', 'verbose_name_plural': 'moves'},
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='move',
            name='effect_percent_chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='move',
            name='effect',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
