# Generated by Django 2.1.7 on 2019-02-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('BATTLE_ITEMS', 'Battle Items'), ('BERRIES', 'Berries'), ('GENERAL_ITEMS', 'General Items'), ('HOLD_ITEMS', 'Hold Items'), ('MACHINES', 'Machines'), ('MEDICINE', 'Medicine'), ('POKEBALLS', 'Pokeballs'), ('UNKOWN', 'Uknown')], max_length=16)),
                ('effect', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Physical'), ('SPECIAL', 'Special'), ('STATUS', 'Status')], max_length=16, null=True)),
                ('power', models.IntegerField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('power_points', models.IntegerField()),
                ('tm', models.CharField(max_length=8, null=True)),
                ('effect', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('form', models.CharField(max_length=32)),
                ('hit_points', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('abilities', models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Ability')),
                ('moves', models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Move')),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', related_query_name='pokemon', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.Type'),
        ),
    ]
