# Generated by Django 2.1.7 on 2019-03-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pokemon', '0002_nature'), ('pokemon', '0003_auto_20190301_0248')]

    dependencies = [
        ('pokemon', '0001_initial_squash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('attack', models.CharField(choices=[('+', 1.1), ('-', 0.9)], max_length=1, null=True)),
                ('defense', models.CharField(choices=[('+', 1.1), ('-', 0.9)], max_length=1, null=True)),
                ('special_attack', models.CharField(choices=[('+', 1.1), ('-', 0.9)], max_length=1, null=True)),
                ('special_defense', models.CharField(choices=[('+', 1.1), ('-', 0.9)], max_length=1, null=True)),
                ('speed', models.CharField(choices=[('+', 1.1), ('-', 0.9)], max_length=1, null=True)),
            ],
        ),
    ]
