# Generated by Django 2.1.7 on 2019-03-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nature',
            options={'verbose_name': 'nature', 'verbose_name_plural': 'natures'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
