# Generated by Django 2.1.7 on 2019-02-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20190223_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BATTLE ITEMS', 'Battle Items'), ('BERRIES', 'Berries'), ('GENERAL ITEMS', 'General Items'), ('HOLD ITEMS', 'Hold Items'), ('MACHINES', 'Machines'), ('MEDICINE', 'Medicine'), ('POKEBALLS', 'Pokeballs'), ('UNKOWN', 'Uknown')], max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
