# Generated by Django 2.1.7 on 2019-02-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20190224_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BATTLE ITEMS', 'Battle Items'), ('BERRIES', 'Berries'), ('GENERAL ITEMS', 'General Items'), ('HOLD ITEMS', 'Hold Items'), ('MACHINES', 'Machines'), ('MEDICINE', 'Medicine'), ('POKEBALLS', 'Pokeballs'), ('UNKOWN', 'Uknown')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
