# Generated by Django 2.1.7 on 2019-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20190224_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='effect_percent_chance',
            field=models.IntegerField(null=True),
        ),
    ]
