# Generated by Django 2.1.7 on 2019-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20190224_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='form',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
