# Generated by Django 2.1.7 on 2019-02-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20190224_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['pokedex', 'form'], 'verbose_name': 'pokemon', 'verbose_name_plural': 'pokemon'},
        ),
    ]
